Fix UI deployment upload
- Mark dns-sync external for esbuild, removing the weird error "Error: Cannot find module './src/cat'""
- Find project config relative to CWD instead of relative to script file